### ISSUE TITLE
Benchmark : UPerf

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/touchstone#1]
We should omit %tile output for `stream`, stick with min/max/mean. For `rr` we should keep the %tile in the output.

**Comment by aakarshg** [comment]
so for the basically we want the aggregations as follows:
```
test_type: stream ( min/max/mean on the keys norm_ltcy/norm_ops/norm_bytes )
test_type: rr ( %percentiles )
```
So for this percentiles which one makes most sense for norm_ltcty and norm_ops and norm_bytes ? 
( 1/99 or 5/95 )

**Comment by jtaleric** [comment]
> so for the basically we want the aggregations as follows:
> 
> ```
> test_type: stream ( min/max/mean on the keys norm_ltcy/norm_ops/norm_bytes )

stream
norm_bytes : min/max/avg

rr
norm_ltcy: avg,90,99%tile
norm_ops : min/max/avg

> test_type: rr ( %percentiles )
> ```
> 
> So for this percentiles which one makes most sense for norm_ltcty and norm_ops and norm_bytes ?
> ( 1/99 or 5/95 )

**Comment by jeniferh** [comment]
Agreed, for stream I typically only care about bytes and rr I focus on latency (ops is nice to have also).  Any way to compare stddev?

**Comment by aakarshg** [comment]
yes we can @jeniferh which key would you like to see the stddev for ?

**Comment by jeniferh** [comment]
I guess most interesting is comparing stddev of bytes/ltcy avg across multiple iterations of each test type, not sure if that is already captured in the reports to be able to compare..

**Comment by aakarshg** [comment]
https://gist.githubusercontent.com/aakarshg/30163c3398fdceecbf72c16e47125030/raw/67721bf9705800c90756b5ab33da92de1a311d81/gistfile1.txt is the new output so maybe this issue can be closed now, and we can keep opening new issues for new suggestions :)

**Comment by jtaleric** [comment]
Thanks!
